#include <bits/stdc++.h>
using namespace std;
static long long modpow(long long a,long long e,long long m){long long r=1;for(;e;e>>=1,a=(__int128)a*a%m)if(e&1)r=(__int128)r*a%m;return r;}
static int leg(long long a,long long p){if(p==2)return (a%8==1||a%8==7)?1:-1; a%=p;if(a<0)a+=p;if(a==0)return 0;return modpow(a,(p-1)/2,p)==1?1:-1;}
static bool isprime64(uint64_t n){if(n<2)return 0;for(uint64_t p:{2ULL,3ULL,5ULL,7ULL,11ULL,13ULL,17ULL,19ULL,23ULL,29ULL,31ULL,37ULL})if(n%p==0)return n==p;uint64_t d=n-1,s=0;while(!(d&1))d>>=1,s++;auto mul=[&](uint64_t a,uint64_t b){return (__uint128_t)a*b%n;};auto pw=[&](uint64_t a,uint64_t e){uint64_t z=1;while(e){if(e&1)z=mul(z,a);a=mul(a,a);e>>=1;}return z;};for(uint64_t a:{2ULL,325ULL,9375ULL,28178ULL,450775ULL,9780504ULL,1795265022ULL}){if(a%n==0)continue;auto x=pw(a%n,d);if(x==1||x==n-1)continue;bool pass=0;for(int i=1;i<s;i++){x=mul(x,x);if(x==n-1){pass=1;break;}}if(!pass)return 0;}return 1;}
static vector<int> plist(int B){vector<char>c(B+1);vector<int>v;for(int i=2;i<=B;i++)if(!c[i]){v.push_back(i);if(1LL*i*i<=B)for(long long j=1LL*i*i;j<=B;j+=i)c[j]=1;}return v;}
struct F{long long q;int e;};
static vector<F> factor(long long n,const vector<int>&P){vector<F>v;for(int q:P){if(1LL*q*q>n)break;if(n%q==0){int e=0;while(n%q==0)n/=q,e++;v.push_back({q,e});}}if(n>1)v.push_back({n,1});return v;}
static long long eg(long long a,long long b,long long&x,long long&y){if(!b){x=1;y=0;return a;}long long X,Y,g=eg(b,a%b,X,Y);x=Y;y=X-a/b*Y;return g;}
static int invm(int a,int m){long long x,y;eg(a,m,x,y);x%=m;if(x<0)x+=m;return x;}
static bool combined_hit(long long p,long long q,const vector<int>&P){long long sig=(q%4==3?1:3); long long k=sig*q; if(k>INT_MAX)return false; long long C=(p+k)/4;auto F=factor(C,P);int kk=(int)k;vector<char>S(kk);S[1%kk]=1;for(auto z:F){vector<int>b;for(int a=0;a<kk;a++)if(S[a])b.push_back(a);long long rr=1;for(int e=1;e<=2*z.e;e++){rr=rr*(z.q%kk)%kk;for(int a:b)S[(long long)a*rr%kk]=1;}}int t1=(kk-invm(4,kk))%kk,t2=(int)((kk-C%kk)%kk);return S[t1]||S[t2];}
static long long next_factor(long long p,long long q,const vector<int>&P){long long sig=(q%4==3?1:3); long long C=(p+sig*q)/4;auto F=factor(C,P);long long best=0;for(auto z:F){if(z.q==p)continue;if(leg(z.q,p)==-1 && (!best||z.q<best))best=z.q;}return best;}
int main(int argc,char**argv){long long LIM=argc>1?atoll(argv[1]):10000000;auto P=plist((int)sqrt((long double)LIM*3)+1000);auto small=plist(10000);set<int>H={1,121,169,289,361,529};long long hard=0,hitBeforeCycle=0,missCycle=0,maxsteps=0;vector<string> bad;
for(long long p=1009;p<LIM;p+=4){if(!isprime64(p)||!H.count(p%840))continue;hard++;long long q0=0;for(int q:small){if(q>=p)break;if(leg(q,p)==-1){q0=q;break;}}if(!q0){cerr<<"no q "<<p<<"\n";continue;}map<long long,int>seen;vector<long long>path;long long q=q0;for(int st=0;st<200;st++){if(seen.count(q)){missCycle++; if(bad.size()<20){ostringstream o;o<<"p="<<p<<" cycle=";for(int i=seen[q];i<(int)path.size();i++)o<<path[i]<<",";bad.push_back(o.str());}break;}seen[q]=path.size();path.push_back(q);if(combined_hit(p,q,P)){hitBeforeCycle++;maxsteps=max<long long>(maxsteps,path.size());break;}long long r=next_factor(p,q,P);if(!r){cerr<<"no edge p="<<p<<" q="<<q<<"\n";break;}q=r;} }
cerr<<"LIM="<<LIM<<" hard="<<hard<<" hitBeforeCycle="<<hitBeforeCycle<<" missCycle="<<missCycle<<" maxsteps="<<maxsteps<<"\n";for(auto&s:bad)cout<<s<<"\n";}
