// exponent2_layers.cpp -- exponent-2 unit-group layers and their sieve dimension.
//
// For hard primes p, p == 1 (mod 24).  For d in {1,2,3,6} and
// d(e)=d, Theorem 3 says that the Type-II layer (d,e) hits iff
// n=p+4e has a divisor == -1 (mod 4d).  Since (Z/4d Z)^* has exponent
// two, this is equivalent to -1 belonging to the subgroup generated by
// the prime-factor residues of n.
#include <bits/stdc++.h>
using namespace std;
using ll = long long;

static vector<int> spf;

static vector<int> prime_residues(ll n, int m) {
  vector<int> out;
  while (n > 1) {
    int q = spf[n];
    out.push_back(q % m);
    while (n % q == 0) n /= q;
  }
  return out;
}

static bool subgroup_hit(ll n, int m) {
  vector<char> seen(m, false);
  seen[1 % m] = true;
  for (int r : prime_residues(n, m)) {
    vector<char> next = seen;
    for (int a = 0; a < m; ++a)
      if (seen[a]) next[(int)(1LL * a * r % m)] = true;
    seen.swap(next);
  }
  return seen[m - 1];
}

static bool atom_hit(ll n, int m) {
  for (int r : prime_residues(n, m))
    if (r == m - 1) return true;
  return false;
}

static vector<vector<int>> odd_characters(int m) {
  vector<int> units;
  for (int a = 1; a < m; ++a)
    if (gcd(a, m) == 1) units.push_back(a);
  vector<vector<int>> chars;
  for (int mask = 0; mask < (1 << units.size()); ++mask) {
    vector<int> chi(m, 0);
    for (size_t i = 0; i < units.size(); ++i)
      chi[units[i]] = (mask >> i & 1) ? -1 : 1;
    if (chi[1] != 1 || chi[m - 1] != -1) continue;
    bool hom = true;
    for (int a : units)
      for (int b : units)
        if (chi[(int)(1LL * a * b % m)] != chi[a] * chi[b]) hom = false;
    if (hom) chars.push_back(move(chi));
  }
  return chars;
}

static bool character_failure(ll n, int m,
                              const vector<vector<int>> &chars) {
  vector<int> residues = prime_residues(n, m);
  for (const auto &chi : chars) {
    bool supported = true;
    for (int r : residues)
      if (chi[r] != 1) supported = false;
    if (supported) return true;
  }
  return false;
}

int main(int argc, char **argv) {
  ll lo = argc > 1 ? atoll(argv[1]) : 0;
  ll limit = argc > 2 ? atoll(argv[2]) : 100000000;
  const vector<pair<int, int>> layers = {
      {1, 1},
      {2, 2}, {2, 4},
      {3, 3}, {3, 9},
      {6, 6}, {6, 12}, {6, 18}, {6, 36},
  };
  const vector<int> hard_classes = {1, 121, 169, 289, 361, 529};

  spf.assign(limit + 4 * 36 + 1, 0);
  for (ll i = 2; i < (ll)spf.size(); ++i)
    if (!spf[i])
      for (ll j = i; j < (ll)spf.size(); j += i)
        if (!spf[j]) spf[j] = (int)i;

  struct Counts {
    ll hard = 0;
    ll exact_fail = 0;
    ll atom_fail = 0;
  } total, by_decade[20];
  map<int, vector<vector<int>>> chars;
  for (int d : {1, 2, 3, 6}) chars[4 * d] = odd_characters(4 * d);
  ll character_mismatches = 0;

  ll start_t = lo / 840;
  for (ll t = start_t;; ++t) {
    bool in_range = false;
    for (int h : hard_classes) {
      ll p = 840 * t + h;
      if (p >= limit) continue;
      in_range = true;
      if (p < max<ll>(lo, 11) || spf[p] != p) continue;

      bool exact_fail = true, atom_fail = true;
      for (auto [d, e] : layers) {
        ll n = p + 4LL * e;
        int m = 4 * d;
        bool hit = subgroup_hit(n, m);
        if (hit) exact_fail = false;
        if (atom_hit(n, m)) atom_fail = false;
        if (character_failure(n, m, chars[m]) != !hit)
          ++character_mismatches;
      }

      int decade = 0;
      for (ll x = p; x >= 10; x /= 10) ++decade;
      ++total.hard;
      ++by_decade[decade].hard;
      if (exact_fail) {
        ++total.exact_fail;
        ++by_decade[decade].exact_fail;
      }
      if (atom_fail) {
        ++total.atom_fail;
        ++by_decade[decade].atom_fail;
      }
    }
    if (!in_range && 840 * t >= limit) break;
  }

  printf("range=[%lld,%lld), exponent-2 layers=%zu\n", lo, limit,
         layers.size());
  printf("layers:");
  for (auto [d, e] : layers) printf(" (%d,%d)", d, e);
  printf("\n\n# exact common failures versus prime-atom sieve survivors\n");
  printf("decade       hard exact_fail exact_rate atom_fail atom_rate\n");
  for (int d = 0; d < 20; ++d) {
    auto c = by_decade[d];
    if (!c.hard) continue;
    printf("10^%-2d %11lld %10lld %10.6f %9lld %9.6f\n", d, c.hard,
           c.exact_fail, (double)c.exact_fail / c.hard, c.atom_fail,
           (double)c.atom_fail / c.hard);
  }
  printf("total %10lld %10lld %10.6f %9lld %9.6f\n", total.hard,
         total.exact_fail, (double)total.exact_fail / total.hard,
         total.atom_fail, (double)total.atom_fail / total.hard);

  // For primes q>36, all e are distinct modulo q.  nu(a) is the number
  // of forbidden p-residues modulo q when q == a (mod 24).
  printf("\n# local prime-atom sieve (q > 36)\n");
  printf("q mod 24   nu(q)\n");
  int nu_sum = 0, phi = 0;
  for (int a = 1; a < 24; ++a) {
    if (gcd(a, 24) != 1) continue;
    int nu = 0;
    for (auto [d, e] : layers)
      if (a % (4 * d) == 4 * d - 1) ++nu;
    printf("%8d %7d\n", a, nu);
    nu_sum += nu;
    ++phi;
  }
  printf("mean nu over reduced classes = %d/%d = %.1f\n", nu_sum, phi,
         (double)nu_sum / phi);
  printf("layer sieve dimension = %.1f; including primality = %.1f\n",
         (double)nu_sum / phi, 1.0 + (double)nu_sum / phi);

  long long assignments = 1;
  printf("\n# exact character separation\nmodulus odd_characters\n");
  for (int m : {4, 8, 12, 24})
    printf("%7d %14zu\n", m, chars[m].size());
  for (auto [d, e] : layers) assignments *= chars[4 * d].size();
  printf("character assignments across nine layers = %lld\n", assignments);
  printf("character/subgroup mismatches = %lld\n", character_mismatches);
  printf("exact-layer sieve dimension = 9/2; including primality = 11/2\n");
}
