// higher_layers.cpp -- audit exponent>2 layers after the nine exponent-2 layers.
//
// For each layer (d,e), compare the exact divisor residues of n=p+4e with
// the subgroup generated by its prime-factor residues modulo 4d.  An exact
// miss is either:
//   character obstruction: target is outside the generated subgroup; or
//   multiplicity obstruction: target is in the subgroup but unavailable
//                             with the actual bounded prime exponents.
#include <bits/stdc++.h>
using namespace std;
using ll = long long;

static vector<int> spf;

struct Factor {
  int q;
  int exponent;
};

static vector<Factor> factor(ll n) {
  vector<Factor> out;
  while (n > 1) {
    int q = spf[n], exponent = 0;
    while (n % q == 0) {
      n /= q;
      ++exponent;
    }
    out.push_back({q, exponent});
  }
  return out;
}

static bool exact_hit(const vector<Factor> &factors, int modulus, int target) {
  vector<char> seen(modulus, false);
  seen[1 % modulus] = true;
  for (auto [q, exponent] : factors) {
    vector<char> next(modulus, false);
    int power = 1;
    for (int j = 0; j <= exponent; ++j) {
      for (int a = 0; a < modulus; ++a)
        if (seen[a]) next[(int)(1LL * a * power % modulus)] = true;
      power = (int)(1LL * power * (q % modulus) % modulus);
    }
    seen.swap(next);
  }
  return seen[target];
}

static vector<char> generated_subgroup(const vector<Factor> &factors,
                                       int modulus) {
  vector<char> seen(modulus, false);
  seen[1 % modulus] = true;
  bool changed = true;
  while (changed) {
    changed = false;
    vector<char> next = seen;
    for (int a = 0; a < modulus; ++a) {
      if (!seen[a]) continue;
      for (auto [q, exponent] : factors) {
        (void)exponent;
        int b = (int)(1LL * a * (q % modulus) % modulus);
        if (!next[b]) {
          next[b] = true;
          changed = true;
        }
      }
    }
    seen.swap(next);
  }
  return seen;
}

static uint64_t extend_subgroup(uint64_t mask, int residue, int modulus) {
  bool changed = true;
  while (changed) {
    changed = false;
    uint64_t next = mask;
    for (int a = 0; a < modulus; ++a)
      if (mask >> a & 1)
        next |= 1ULL << (int)(1LL * a * residue % modulus);
    if (next != mask) {
      mask = next;
      changed = true;
    }
  }
  return mask;
}

static vector<uint64_t> all_subgroups(int modulus) {
  vector<int> units;
  for (int a = 1; a < modulus; ++a)
    if (gcd(a, modulus) == 1) units.push_back(a);
  set<uint64_t> known{1ULL << 1};
  vector<uint64_t> groups{1ULL << 1};
  for (size_t i = 0; i < groups.size(); ++i)
    for (int residue : units) {
      uint64_t next = extend_subgroup(groups[i], residue, modulus);
      if (known.insert(next).second) groups.push_back(next);
    }
  return groups;
}

static int escape_cost(const vector<Factor> &factors, int modulus, int target,
                       const vector<uint64_t> &subgroups) {
  int best = numeric_limits<int>::max();
  for (uint64_t subgroup : subgroups) {
    if (subgroup >> target & 1) continue;
    int cost = 0;
    for (auto [q, exponent] : factors)
      if (!(subgroup >> (q % modulus) & 1)) cost += exponent;
    best = min(best, cost);
  }
  return best;
}

struct Layer {
  int d;
  int e;
};

int main(int argc, char **argv) {
  ll lo = argc > 1 ? atoll(argv[1]) : 1000000;
  ll limit = argc > 2 ? atoll(argv[2]) : 100000000;
  const vector<Layer> exponent_two = {
      {1, 1},
      {2, 2}, {2, 4},
      {3, 3}, {3, 9},
      {6, 6}, {6, 12}, {6, 18}, {6, 36},
  };
  const vector<Layer> higher = {
      {4, 8}, {4, 16},
      {5, 5}, {5, 25},
      {7, 7}, {7, 49},
      {8, 32}, {8, 64},
  };
  const vector<int> hard_classes = {1, 121, 169, 289, 361, 529};

  spf.assign(limit + 4 * 64 + 1, 0);
  for (ll i = 2; i < (ll)spf.size(); ++i)
    if (!spf[i])
      for (ll j = i; j < (ll)spf.size(); j += i)
        if (!spf[j]) spf[j] = (int)i;

  struct LayerCounts {
    ll hit = 0;
    ll character_miss = 0;
    ll multiplicity_miss = 0;
    int max_escape_cost = 0;
    int residual_max_escape_cost = 0;
  };
  vector<LayerCounts> counts(higher.size());
  map<int, vector<uint64_t>> subgroups;
  for (int d : {4, 5, 7, 8}) subgroups[4 * d] = all_subgroups(4 * d);
  ll hard = 0, baseline_fail = 0, all_higher_fail = 0;
  map<int, ll> residual_character_layers;
  map<int, ll> residual_multiplicity_layers;
  map<int, ll> first_by_character_layers;
  vector<pair<ll, pair<int, int>>> examples;

  for (ll t = lo / 840;; ++t) {
    bool in_range = false;
    for (int h : hard_classes) {
      ll p = 840 * t + h;
      if (p >= limit) continue;
      in_range = true;
      if (p < max<ll>(lo, 11) || spf[p] != p) continue;
      ++hard;

      bool baseline_hit = false;
      for (auto [d, e] : exponent_two) {
        int modulus = 4 * d;
        ll n = p + 4LL * e;
        int target = (int)((-n % modulus + modulus) % modulus);
        if (exact_hit(factor(n), modulus, target)) baseline_hit = true;
      }
      if (baseline_hit) continue;
      ++baseline_fail;

      bool any_higher_hit = false;
      int character_layers = 0, multiplicity_layers = 0;
      vector<int> escape_costs(higher.size(), 0);
      for (size_t i = 0; i < higher.size(); ++i) {
        auto [d, e] = higher[i];
        int modulus = 4 * d;
        ll n = p + 4LL * e;
        int target = (int)((-n % modulus + modulus) % modulus);
        vector<Factor> factors = factor(n);
        bool hit = exact_hit(factors, modulus, target);
        bool subgroup_hit = generated_subgroup(factors, modulus)[target];
        if (hit) {
          ++counts[i].hit;
          any_higher_hit = true;
        } else if (subgroup_hit) {
          ++counts[i].multiplicity_miss;
          ++multiplicity_layers;
          escape_costs[i] =
              escape_cost(factors, modulus, target, subgroups[modulus]);
          counts[i].max_escape_cost =
              max(counts[i].max_escape_cost, escape_costs[i]);
        } else {
          ++counts[i].character_miss;
          ++character_layers;
        }
      }
      if (!any_higher_hit) {
        ++all_higher_fail;
        ++residual_character_layers[character_layers];
        ++residual_multiplicity_layers[multiplicity_layers];
        if (!first_by_character_layers.count(character_layers))
          first_by_character_layers[character_layers] = p;
        for (size_t i = 0; i < higher.size(); ++i)
          counts[i].residual_max_escape_cost =
              max(counts[i].residual_max_escape_cost, escape_costs[i]);
        if (examples.size() < 30)
          examples.push_back({p, {character_layers, multiplicity_layers}});
      }
    }
    if (!in_range && 840 * t >= limit) break;
  }

  printf("range=[%lld,%lld) hard=%lld baseline-nine-fail=%lld all-17-fail=%lld\n",
         lo, limit, hard, baseline_fail, all_higher_fail);
  printf("\n# conditional on failure of all nine exponent-2 layers\n");
  printf(" d   e       hit  character_miss  multiplicity_miss max_escape residual_max\n");
  for (size_t i = 0; i < higher.size(); ++i)
    printf("%2d %3d %10lld %15lld %18lld %10d %12d\n", higher[i].d, higher[i].e,
           counts[i].hit, counts[i].character_miss,
           counts[i].multiplicity_miss, counts[i].max_escape_cost,
           counts[i].residual_max_escape_cost);

  printf("\n# obstruction-layer counts among primes failing all 17 layers\n");
  printf("character_layers count first_p\n");
  for (auto [layers, count] : residual_character_layers)
    printf("%16d %5lld %lld\n", layers, count,
           first_by_character_layers[layers]);
  printf("multiplicity_layers count\n");
  for (auto [layers, count] : residual_multiplicity_layers)
    printf("%19d %lld\n", layers, count);

  printf("\n# first residual examples: p character_layers multiplicity_layers\n");
  for (auto [p, obstruction] : examples)
    printf("%lld %d %d\n", p, obstruction.first, obstruction.second);
}
