#include <bits/stdc++.h>
using namespace std;
static uint64_t mulm(uint64_t a,uint64_t b,uint64_t m){return (__uint128_t)a*b%m;} static uint64_t powm(uint64_t a,uint64_t e,uint64_t m){uint64_t z=1;while(e){if(e&1)z=mulm(z,a,m);a=mulm(a,a,m);e>>=1;}return z;}
static bool isp(uint64_t n){if(n<2)return 0;for(uint64_t p:{2ULL,3ULL,5ULL,7ULL,11ULL,13ULL,17ULL,19ULL,23ULL,29ULL,31ULL,37ULL})if(n%p==0)return n==p;uint64_t d=n-1,s=0;while(!(d&1))d>>=1,s++;for(uint64_t a:{2ULL,325ULL,9375ULL,28178ULL,450775ULL,9780504ULL,1795265022ULL}){if(a%n==0)continue;auto x=powm(a%n,d,n);if(x==1||x==n-1)continue;bool pass=0;for(int i=1;i<s;i++){x=mulm(x,x,n);if(x==n-1){pass=1;break;}}if(!pass)return 0;}return 1;}
static int leg(uint64_t p,int r){auto z=powm(p%r,(r-1)/2,r);return z==1?1:(z==0?0:-1);} static vector<int> plist(int B){vector<char>c(B+1);vector<int>v;for(int i=2;i<=B;i++)if(!c[i]){v.push_back(i);if(1LL*i*i<=B)for(long long j=1LL*i*i;j<=B;j+=i)c[j]=1;}return v;}
static long long eg(long long a,long long b,long long&x,long long&y){if(!b){x=1;y=0;return a;}long long X,Y,g=eg(b,a%b,X,Y);x=Y;y=X-a/b*Y;return g;} static int invm(int a,int m){long long x,y;eg(a,m,x,y);x%=m;if(x<0)x+=m;return x;}
static set<int>P(int k,uint64_t x){int a=x%k;return {1,a,(int)(1LL*a*a%k)};} static set<int> muls(int k,const set<int>&A,const set<int>&B){set<int>C;for(int a:A)for(int b:B)C.insert(1LL*a*b%k);return C;} static set<int> D(int k,int s){set<int>x={1};for(int q:{2,3,5,7})if(s%q==0)x=muls(k,x,P(k,q));return x;}
static bool mhit(uint64_t p,int r,int&kout){uint64_t N=(p+3)/4;int j=(r-N%r)%r;int k=4*j+3;kout=k;uint64_t C=N+j;if(C%r)return 0;int s=gcd((uint64_t)210,C);if(s%r==0)return 0;uint64_t m=C/(uint64_t(s)*r);auto B=muls(k,D(k,s),P(k,r));B=muls(k,B,P(k,m));int t1=(k-invm(4,k))%k,t2=(k-C%k)%k;return B.count(t1)||B.count(t2);}
int main(int argc,char**argv){int WANT=argc>1?atoi(argv[1]):50000;uint64_t LO=argc>2?strtoull(argv[2],0,10):100000000ULL,HI=argc>3?strtoull(argv[3],0,10):1000000000000000ULL;int RB=argc>4?atoi(argv[4]):10000;auto R=plist(RB);int hs[6]={1,121,169,289,361,529};mt19937_64 gen(123456789);map<int,long long> byh,maxrankh,maxrh;long long got=0,fail=0,maxrank=0,maxr=0;uint64_t worstp=0;vector<uint64_t> bad;while(got<WANT){uint64_t span=(HI-LO)/840;uint64_t t=gen()%span+LO/840;int h=hs[gen()%6];uint64_t p=840*t+h;if(p<LO||p>=HI||!isp(p))continue;got++;byh[h]++;int rank=0,fr=0,fk=0;for(int r:R){if(r<=7||r>=p)continue;if(leg(p,r)!=-1)continue;rank++;int k;if(mhit(p,r,k)){fr=r;fk=k;break;}}if(!fr){fail++;if(bad.size()<20)bad.push_back(p);}else{maxrankh[h]=max<long long>(maxrankh[h],rank);maxrh[h]=max<long long>(maxrh[h],fr);if(rank>maxrank){maxrank=rank;maxr=fr;worstp=p;}}}
cerr<<"got="<<got<<" fail="<<fail<<" maxrank="<<maxrank<<" maxr_at_maxrank="<<maxr<<" worstp="<<worstp<<"\n";for(int h:hs)cout<<"h="<<h<<" n="<<byh[h]<<" maxrank="<<maxrankh[h]<<" maxr="<<maxrh[h]<<"\n";for(auto p:bad)cout<<"BAD "<<p<<"\n";}
